workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: "3.22.2" # إصدار Flutter (استبدله بإصدارك)
      xcode: "15.3" # إصدار Xcode
      cocoapods: "default" # أو حدد إصدارًا معينًا مثل "1.15.2"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          flutter precache --ios

      - name: Install iOS dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ahmadalhmoud717@gmail.com
