name: Build unsigned iOS IPA

on:
  workflow_dispatch:

jobs:
  build-unsigned-ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Flutter clean
        run: flutter clean

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Remove iOS Pods and Podfile.lock
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all || true

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods --no-document || true
          pod --version

      - name: Run pod install
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS for Simulator (build Flutter.framework)
        run: flutter build ios --simulator

      - name: Build iOS release (no codesign)
        run: flutter build ios --release --no-codesign --no-simulator

      - name: Package unsigned IPA
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r MyApp-unsigned.ipa Payload

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/MyApp-unsigned.ipa
