name: Build unsigned iOS IPA

on:
  workflow_dispatch:

jobs:
  build-unsigned-ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Run flutter pub get
        run: flutter pub get

      - name: Run pod install
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS release (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        run: |
          APP_PATH="build/ios/iphoneos/Runner.app"
          IPA_DIR="build/ios/ipa"
          mkdir -p "$IPA_DIR/Payload"
          cp -R "$APP_PATH" "$IPA_DIR/Payload/"
          cd "$IPA_DIR"
          zip -r "MyApp-unsigned.ipa" Payload

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/MyApp-unsigned.ipa
